site_name: ARYSSA
theme:
  name: material
  # Palette toggle for automatic mode
  palette:
    - media: "(prefers-color-scheme)"
      toggle:
        icon: material/brightness-auto
        name: Switch to light mode

    # Palette toggle for light mode
    - media: "(prefers-color-scheme: light)"
      scheme: default
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode

    # Palette toggle for dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      toggle:
        icon: material/brightness-4
        name: Switch to system preference
extra_css:
  - stylesheets/extra.css
# markodown f.e note alert bug ...
markdown_extensions:
  - admonition
  - pymdownx.details
  - pymdownx.superfences
  - tables
nav:
  - index.md
  - Docker:
      - Overview: sections/docker/overview.md
      - Commands: sections/docker/commands.md
      - Getting Started: sections/docker/start.md
  - Backend:
      - Introduction: sections/back/api-introduction.md
      - Structure: sections/back/api-structure.md
      - Installing: sections/back/api-install.md
      - Requests: sections/back/api-requests.md
  - How to edit documentation: sections/info/documentation.md
